from enum import StrEnum


USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256

PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6

PROJECTS_PER_PAGE = 12
USERS_PER_PAGE = 12

AVATAR_SIZE = 256
AVATAR_FONT_SIZE_RATIO = 0.52
AVATAR_TEXT_COLOR = "#FFFFFF"
AVATAR_MODE = "RGB"
AVATAR_FORMAT = "PNG"
AVATAR_FONT_NAME = "arial.ttf"

PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"


class AvatarColor(StrEnum):
    BLUE = "#8FAADC"
    GREEN = "#93C47D"
    ORANGE = "#F6B26B"
    PURPLE = "#C9A0DC"
    TEAL = "#76A5AF"


AVATAR_COLORS = tuple(color.value for color in AvatarColor)
